### ISSUE TITLE
Camera access privacy-sensitive 

### ISSUE THREAD

**Issue by EliMal** [matthutchinson/videosnap#15]
I use command line tool app and i have a crash because "because it attempted to access privacy-sensitive data without a usage description".

I tried to build my own command line tool which record from connected camera but I get the same issue. I tried to add info.plist with NSCameraUsageDescription key and add Request authorization for Capture function but i didn't get any success. It crashes and I get the same error.

**Comment by allankenneth** [comment]
Just a shot in the dark: The first time you run the program, a brief dialog comes up asking to allow camera access. Is it possible you may have accidentally disallowed this camera access the first time you ran the program?

Under Preferences > Security & Privacy under Camera, see if Terminal is listed. If it's unchecked, check it and try again.

I'm betting this won't help, but ya never know :)

**Comment by EliMal** [comment]
The problem that I don't get this camera permission dialog although I implement check of permission(not determined) and request access. The app crashed when it try to add the camera, which he recognize,  as AVCaptureDeviceInput.

**Comment by stang2019** [comment]
I want to use it as the debugger engine of my camera driver, so I run it via Xcode debug, in this case, the camera permission window will not show(run from terminal it shows), and system (10.14) won't allow  manually add, any work around?

**Comment by matthutchinson** [comment]
This should be resolved in the latest version (0.0.5) since I'm now embedding `Info.plist` (containing the `NSCameraUsageDescription` key) into the binary with [this technique](https://red-sweater.com/blog/2083/the-power-of-plist) i.e. adding this as an extra linker flags.

    -sectcreate __TEXT __info_plist $(INFOPLIST_FILE)

This works, except when running videosnap within Xcode.  The only way I've found to fix it for that scenario, is to [add a new Build Phase](https://samwize.com/2019/10/13/info-plist-for-a-macos-command-line-app/) to copy the `Info.plist` file into the target folder. That way, since it's sitting alongside the binary, Xcode can find it.  The latest videosnap Xcode project file now has this configured.

If you still have issues let me know.

🙇 Thanks to @ptsochantaris for helping me debug all this over Slack!

**Comment by matthutchinson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Feedback form changes (show/edit time to auto-send and button to send now)](https://trello.com/c/3oNYZrdb/96-feedback-form-changes-show-edit-time-to-auto-send-and-button-to-send-now)
